version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_HOST: "mysql"
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      - mysql
  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS:-pass}
      MYSQL_USER: ${DBUSER:-user}
      MYSQL_PASSWORD: ${DBPASS:-pass}
      MYSQL_DATABASE: docker_compose_ecs_rails_sample
      TZ: "Asia/Tokyo"
    volumes:
      - "mysql_data:/var/lib/mysql"
volumes:
  mysql_data: