default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: docker_compose_ecs_rails_sample

development:
  <<: *default
  host: 127.0.0.1
  username: root
  password: pass

production:
  <<: *default
  host: host.docker.internal
  username: root
  password: pass
  # password: <%= ENV['DOCKER_COMPOSE_ECS_RAILS_SAMPLE_DATABASE_PASSWORD'] %>
